name: Bug report 🐛
description: Report a bug
labels: ["category.bug", "status.needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please check if an existing issue already exists. Thanks for taking the time to improve Taiko!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A concise description of the problem and what you expected to happen.
      value: Description of the bug here.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug, a numbered list could be good.
      value: Steps to reproduce here.
